name: petaholiic_admin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  google_fonts: ^4.0.3
  shimmer: ^2.0.0
  iconsax: ^0.0.8
  flutter_launcher_icons: "^0.13.1"
  mailer: ^6.2.0
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ellaspizza-logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
